### ISSUE TITLE
adding TOSCA support for disk type selection

### ISSUE THREAD

**Issue by spigad** [indigo-dc/im#262]
As briefly discussed with Miguel, we would need  to be able to select the disk type while creating disk to be attached to a VM. 
Use case is related to  XCache that we need to create within DODAS cluster. For scalability purposes we'd like to use SSD disks..

**Comment by micafer** [comment]
Hi @spigad:

In the devel branch we add support to this.
You have to change the type of the storage from `tosca.nodes.BlockStorage` to `tosca.nodes.indigo.BlockStorage` and add the type, in the case of GCE set `pd-ssd`:

```yaml
    my_block_storage:
      type: tosca.nodes.indigo.BlockStorage
      properties:
        size: 10GB
        type: pd-ssd
```
